### ISSUE TITLE
Planning for Release 7

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#135]

**Comment by ifoche** [comment]
Maximum priority:
- [ ] Introduce a progress bar on Activity change to show something when things are being done in background (Card #84)
- [ ] Introduce a Settings activity
- [ ] DHIS Pull (Card #32)
- [ ] Include Checkbox/Radiobutton questions and implement on them the needed logic: if it is a radiobutton, we need that pressing a selected radio removes selection. If it is a checkbox, then only one at a time should be allowed
- [ ] Introduce a checkbox in Settings to show/hide num/dems
- [ ] Introduce a switch in Settings to decide whether or not we need to use system defined fond settings. In case answer is no, provide a slidebar to customize font sizes

Medium priority:
- [ ] Implement needed functionality for being able to reinstall DB without needing to uninstall the whole app (Card #74)
- [ ] DHIS Push (Card #23)
- [ ] Footer background should be filling (with a different color) proportionally to the ratio questions answered/questions not answered
- [ ] Organize dataElements from DHIS side to be able to properly manage relation between tab, header and questions in this side

Low priority:
- [ ] Put in Settings Activity a field for introducing DHIS server URL to upload/download data to/from. Check that minimum server version is 2.17
- [ ] When app opens, if we've got internet, we have to check each survey version, whether we have all the orgunits and we have to download the future planning. While this is being done (recovering every org units which the user has access to and, for each org unit, look for the surveys that he has associated (programs). We have to show the progress bar with a message saying something like "retrieving XX org. units / retrieving XX surveys / etc). 

- For security issues that we may take into account, see #100

- Development is made in 2 different sprints: 
   - UI sprint. Next sprint:
   - backend sprint (pull/push/etc). Next sprint:

**Comment by ifoche** [comment]
This planning is for every @EyeSeeTea/developers
