### ISSUE TITLE
Designing push/pull

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/malariapp#219]
Things to keep in mind:
- [Big Picture Diagram](https://www.lucidchart.com/documents/edit/43004bd8-509e-468b-864a-139ff141b642) (to be improved)
- Pull task is about metadata while push is about data.
- At least in the very first version when pulling an alert will be displayed saying sth like "You are about to destroy any survey in progress. Do you really want to go on with the pulling?"

Short term tasks:
- [x] Direct push to DHIS (@josemp10) Specific Card: #23 
- [ ] Integrate DHIS SDK (@ifoche) Specific Card: #32
- [ ] Develop new features in DHIS SDK and PR (@adrianq) Specific Card: #158

Medium term tasks:
- [ ] Pull from DHIS SDK to app
- [ ] Push from app to DHIS SDK

**Comment by ifoche** [comment]
Pull is waiting for PSI/Knowming approval

**Comment by adrianq** [comment]
Design has been done and approved  by PSI/Knowming. Just waiting for comments...
