### ISSUE TITLE
Bring some tasks from pictureapp

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#520]

**Comment by ifoche** [comment]
- [ ] EyeSeeTea/pictureapp#135 - Modal dialogs - commit [here](https://github.com/EyeSeeTea/pictureapp/commit/7744b6a647605421fb8206be59b864641d32b6f2)
- [ ] EyeSeeTea/pictureapp#132 - License returns - branch [here](https://github.com/EyeSeeTea/pictureapp/commits/license_text)
- [ ] EyeSeeTea/pictureapp#117 - Permissions to avoid Google Play automatically add them - PR [here](https://github.com/EyeSeeTea/pictureapp/pull/126)

**Comment by idelcano** [comment]
The first task is not necesary.

**Comment by idelcano** [comment]
@ifoche i think we can close this card.
