### ISSUE TITLE
Comments from Rodolfo + Martin for release 6

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#95]

**Comment by ifoche** [comment]
This issue is for @EyeSeeTea/owners

**Comment by ifoche** [comment]
Issue related to #72

**Comment by ifoche** [comment]
Maximum priority (para el sábado):
- [ ] Meter un progress bar para hacer en background el trabajo cuando se pulsa en un Survey (Card #84)
- [ ] Feedback mockup generando números aleatorios y con Traffic Light (Card #90)

Medium priority:
- [ ] Implementar la funcionalidad necesaria para poder reinstalar la DB sin tener que desinstalar la aplicación (Card #74)
- [ ] Preguntas con (num||den) == 0 && no es pregunta padre no se presenta el 0 sino un espacio  en blanco en su lugar (Card #77)
- [ ] Enviar un portfolio de nuestro diseñador a Rodolfo (Card #80)
- [ ] Movida dinámica de listado de orgunits (Jose ha prestado atención). Relacionado con el push a DHIS (Card #81)
- [ ] DHIS Pull tiene horizonte temporal corto (habría que ir empezándolo ya) (Card #32)
- [ ] Push tiene un horizonte a medio plazo (Card #23)
- [ ] No se pueden crear varias surveys para un mismo orgunit en estado "sin terminar" (añadir validación). Cuando un survey se termina, se pasa a un estado "finished" y se guarda en la DB para las Analytics (Card #83)
- [ ] Añadir en la DB un campo "Status" donde se pueda determinar el cambio de estado entre "en desarrollo" --> "completed" -->"sent to DHIS" (Card #85)
